export const FETCH_MESSAGES_REQUEST  = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS  = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE  = 'FETCH_MESSAGES_FAILURE';
export const FETCH_TOKEN_CHECK       = 'FETCH_TOKEN_CHECK';
export const FETCH_EXITING_APP       = 'FETCH_EXITING_APP';