export const FETCH_MESSAGES_REQUEST: string = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS: string = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE: string = 'FETCH_MESSAGES_FAILURE';
export const FETCH_TOKEN_CHECK     : string = 'FETCH_TOKEN_CHECK';
export const FETCH_EXITING_APP     : string = 'FETCH_EXITING_APP';