export const FETCH_DIALOGS = "FETCH_DIALOGS";
export const FETCH_DIALOGS_SET = "FETCH_DIALOGS_SET";

export const FETCH_ACTIONS = "FETCH_ACTION";
export const FETCH_MESSAGES = "FETCH_MESSAGES";

export const FETCH_FILTERED_DIALOGS = "FETCH_FILTERED_DIALOGS";
export const FETCH_FILTERED_SET = "FETCH_FILTERED_SET";
