export const FETCH_REGISTRATION_REQUEST: string = "FETCH_REGISTRATION_REQUEST";
export const FETCH_REGISTRATION_SUCCESS: string = "FETCH_REGISTRATION_SUCCESS";
export const FETCH_REGISTRATION_FAILURE: string = "FETCH_REGISTRATION_FAILURE";