export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SET = "FETCH_USER_SET";
export const FETCH_USER_UPDATE = "FETCH_USER_UPDATE";

export const FETCH_USER_SETTINGS = "FETCH_USER_SETTINGS";
export const FETCH_USER_SETTINGS_SET = "FETCH_USER_SETTINGS_SET";
